import { SidebarGroup } from './sidebar.model';
import { ROLE, FULL_PERMISSION } from '../../core/config/functions.constants';

/**
 * Sidebar hoàn chỉnh tương lai — phẳng tuyệt đối 2 cấp
 * - Không còn child.children (max 2 cấp: Parent -> Child)
 * - Nhóm theo luồng nghiệp vụ, map đủ 60 nhóm quyền (199 perms BE)
 * - Trang hiện hữu (procurement/system) đặt đúng nhóm tương lai,
 *   trang chưa triển khai -> route tới coming-soon (trang trắng)
 */
export const SIDEBAR_MENU: SidebarGroup[] = [
  {
    kind: 'group',
    id: 'overview',
    title: 'TỔNG QUAN',
    items: [
      {
        kind: 'parent',
        id: 'home',
        title: 'Dashboard',
        icon: 'dashboard',
        route: '/admin/home',
        children: [],
      },
      {
        kind: 'parent',
        id: 'store-client',
        title: 'Xem Cửa Hàng (Client)',
        icon: 'shop',
        route: '/store',
        children: [],
      },
    ],
  },
  {
    kind: 'group',
    id: 'pos-group',
    title: 'BÁN HÀNG',
    items: [
      {
        kind: 'parent',
        id: 'pos',
        title: 'Bán hàng (POS)',
        icon: 'shopping-cart',
        children: [
          {
            kind: 'child',
            id: 'pos-orders',
            title: 'Đơn hàng',
            route: '/admin/pos/orders/list',
            activePrefix: '/admin/pos/orders',
            authorities: [ROLE.DON_HANG.VIEW],
          },
          {
            kind: 'child',
            id: 'pos-delivery',
            title: 'Giao hàng',
            route: '/admin/pos/deliveries/list',
            activePrefix: '/admin/pos/deliveries',
            authorities: [ROLE.GIAO_HANG.VIEW],
          },
          {
            kind: 'child',
            id: 'pos-kds',
            title: 'Bếp (KDS)',
            route: '/admin/pos/kds/list',
            activePrefix: '/admin/pos/kds',
            authorities: [ROLE.KDS_TICKET.VIEW],
          },
          {
            kind: 'child',
            id: 'pos-refund',
            title: 'Hoàn tiền',
            route: '/admin/pos/refunds/list',
            activePrefix: '/admin/pos/refunds',
            authorities: [ROLE.HOAN_TIEN.VIEW],
          },
          {
            kind: 'child',
            id: 'pos-payment',
            title: 'Thanh toán',
            route: '/admin/pos/payments/list',
            activePrefix: '/admin/pos/payments',
            authorities: [ROLE.Y_DINH_THANH_TOAN.VIEW],
          },
        ],
      },
    ],
  },
  {
    kind: 'group',
    id: 'store-group',
    title: 'VẬN HÀNH CỬA HÀNG',
    items: [
      {
        kind: 'parent',
        id: 'store-ops',
        title: 'Cửa hàng',
        icon: 'appstore',
        children: [
          {
            kind: 'child',
            id: 'store-shift',
            title: 'Ca làm việc',
            route: '/admin/store/shifts/list',
            activePrefix: '/admin/store/shifts',
            authorities: [ROLE.CA_LAM_VIEC.VIEW],
          },
          {
            kind: 'child',
            id: 'store-assignment',
            title: 'Phân ca',
            route: '/admin/store/assignments/list',
            activePrefix: '/admin/store/assignments',
            authorities: [ROLE.PHAN_CA.VIEW],
          },
          {
            kind: 'child',
            id: 'store-report',
            title: 'Báo cáo ngày',
            route: '/admin/store/reports/list',
            activePrefix: '/admin/store/reports',
            authorities: [ROLE.BAO_CAO_NGAY.VIEW],
          },
          {
            kind: 'child',
            id: 'store-stock',
            title: 'Tồn sản phẩm',
            route: '/admin/store/product-stock/list',
            activePrefix: '/admin/store/product-stock',
            authorities: [ROLE.XEM_TON_SAN_PHAM.VIEW],
          },
        ],
      },
    ],
  },
  {
    kind: 'group',
    id: 'menu-group',
    title: 'THỰC ĐƠN',
    items: [
      {
        kind: 'parent',
        id: 'menu-mgmt',
        title: 'Thực đơn',
        icon: 'coffee',
        children: [
          {
            kind: 'child',
            id: 'menu-category',
            title: 'Danh mục',
            route: '/admin/menu/categories/list',
            activePrefix: '/admin/menu/categories',
            authorities: [ROLE.DANH_MUC.VIEW],
          },
          {
            kind: 'child',
            id: 'menu-product',
            title: 'Sản phẩm',
            route: '/admin/menu/products/list',
            activePrefix: '/admin/menu/products',
            authorities: [ROLE.SAN_PHAM.VIEW],
          },
          {
            kind: 'child',
            id: 'menu-variant',
            title: 'Biến thể',
            route: '/admin/menu/variants/list',
            activePrefix: '/admin/menu/variants',
            authorities: [ROLE.BIEN_THE_SAN_PHAM.VIEW],
          },
          {
            kind: 'child',
            id: 'menu-topping',
            title: 'Topping',
            route: '/admin/menu/toppings/list',
            activePrefix: '/admin/menu/toppings',
            authorities: [ROLE.TOPPING.VIEW],
          },
          {
            kind: 'child',
            id: 'menu-combo',
            title: 'Combo',
            route: '/admin/menu/combos/list',
            activePrefix: '/admin/menu/combos',
            authorities: [ROLE.COMBO.VIEW],
          },
          {
            kind: 'child',
            id: 'menu-voucher',
            title: 'Voucher',
            route: '/admin/menu/vouchers/list',
            activePrefix: '/admin/menu/vouchers',
            authorities: [ROLE.VOUCHER.VIEW],
          },
        ],
      },
      {
        kind: 'parent',
        id: 'menu-ops',
        title: 'Vận hành món',
        icon: 'control',
        children: [
          {
            kind: 'child',
            id: 'menu-bom',
            title: 'Định lượng (BOM)',
            route: '/admin/menu/bom/list',
            activePrefix: '/admin/menu/bom',
            authorities: [ROLE.DINH_LUONG_BOM.VIEW],
          },
          {
            kind: 'child',
            id: 'menu-availability',
            title: 'Khả dụng CN',
            route: '/admin/menu/availability/list',
            activePrefix: '/admin/menu/availability',
            authorities: [ROLE.SAN_PHAM_KHA_DUNG.VIEW],
          },
        ],
      },
    ],
  },
  {
    kind: 'group',
    id: 'inventory-group',
    title: 'KHO & CUNG ỨNG',
    items: [
      {
        kind: 'parent',
        id: 'inv',
        title: 'Kho',
        icon: 'inbox',
        children: [
          {
            kind: 'child',
            id: 'inv-warehouse',
            title: 'Kho',
            route: '/admin/inventory/warehouses/list',
            activePrefix: '/admin/inventory/warehouses',
            authorities: [ROLE.KHO.VIEW],
          },
          {
            kind: 'child',
            id: 'inv-material',
            title: 'Nguyên vật liệu',
            route: '/admin/inventory/materials/list',
            activePrefix: '/admin/inventory/materials',
            authorities: [ROLE.NGUYEN_VAT_LIEU.VIEW],
          },
          {
            kind: 'child',
            id: 'inv-balance',
            title: 'Tồn kho',
            route: '/admin/inventory/balances/list',
            activePrefix: '/admin/inventory/balances',
            authorities: [ROLE.XEM_TON_KHO.VIEW],
          },
          {
            kind: 'child',
            id: 'inv-in',
            title: 'Nhập kho',
            route: '/admin/inventory/stock-in/list',
            activePrefix: '/admin/inventory/stock-in',
            authorities: [ROLE.NHAP_KHO.VIEW],
          },
          {
            kind: 'child',
            id: 'inv-out',
            title: 'Xuất kho',
            route: '/admin/inventory/stock-out/list',
            activePrefix: '/admin/inventory/stock-out',
            authorities: [ROLE.XUAT_KHO.VIEW],
          },
          {
            kind: 'child',
            id: 'inv-transfer',
            title: 'Chuyển kho',
            route: '/admin/inventory/transfers/list',
            activePrefix: '/admin/inventory/transfers',
            authorities: [ROLE.CHUYEN_KHO.VIEW],
          },
          {
            kind: 'child',
            id: 'inv-count',
            title: 'Kiểm kê',
            route: '/admin/inventory/counts/list',
            activePrefix: '/admin/inventory/counts',
            authorities: [ROLE.KIEM_KE.VIEW],
          },
        ],
      },
      {
        kind: 'parent',
        id: 'proc',
        title: 'Mua hàng',
        icon: 'shopping',
        children: [
          {
            kind: 'child',
            id: 'proc-supplier',
            title: 'Nhà cung cấp',
            route: '/admin/procurement/suppliers/list',
            activePrefix: '/admin/procurement/suppliers',
            authorities: [ROLE.NHA_CUNG_CAP.VIEW],
          },
          {
            kind: 'child',
            id: 'proc-price',
            title: 'Bảng giá NCC',
            route: '/admin/procurement/supplier-materials/list',
            activePrefix: '/admin/procurement/supplier-materials',
            authorities: [ROLE.BANG_GIA_NCC.VIEW],
          },
          {
            kind: 'child',
            id: 'proc-po',
            title: 'Đơn mua hàng',
            route: '/admin/procurement/purchase-orders/list',
            activePrefix: '/admin/procurement/purchase-orders',
            authorities: [ROLE.DON_MUA_HANG.VIEW],
          },
        ],
      },
    ],
  },
  {
    kind: 'group',
    id: 'finance-group',
    title: 'TÀI CHÍNH',
    items: [
      {
        kind: 'parent',
        id: 'fin',
        title: 'Tài chính',
        icon: 'dollar',
        children: [
          {
            kind: 'child',
            id: 'fin-payable',
            title: 'Công nợ NCC',
            route: '/admin/finance/payables/list',
            activePrefix: '/admin/finance/payables',
            authorities: [ROLE.CONG_NO_PHAI_TRA.VIEW],
          },
          {
            kind: 'child',
            id: 'fin-expense',
            title: 'Chi phí',
            route: '/admin/finance/expenses/list',
            activePrefix: '/admin/finance/expenses',
            authorities: [ROLE.CHI_PHI.VIEW],
          },
          {
            kind: 'child',
            id: 'fin-summary',
            title: 'Tổng hợp CN',
            route: '/admin/finance/summaries/list',
            activePrefix: '/admin/finance/summaries',
            authorities: [ROLE.TONG_HOP_TAI_CHINH.VIEW],
          },
        ],
      },
    ],
  },
  {
    kind: 'group',
    id: 'customer-group',
    title: 'KHÁCH HÀNG',
    items: [
      {
        kind: 'parent',
        id: 'crm',
        title: 'Khách hàng',
        icon: 'team',
        children: [
          {
            kind: 'child',
            id: 'crm-list',
            title: 'Khách hàng',
            route: '/admin/system/customers/list',
            activePrefix: '/admin/system/customers',
            authorities: [ROLE.KHACH_HANG.VIEW],
          },
          {
            kind: 'child',
            id: 'crm-loyalty',
            title: 'Loyalty',
            route: '/admin/customer/loyalty/list',
            activePrefix: '/admin/customer/loyalty',
            authorities: [ROLE.KHACH_HANG_LOYALTY.VIEW],
          },
        ],
      },
    ],
  },
  {
    kind: 'group',
    id: 'system-group',
    title: 'HỆ THỐNG',
    items: [
      {
        kind: 'parent',
        id: 'sys-org',
        title: 'Tổ chức',
        icon: 'apartment',
        children: [
          {
            kind: 'child',
            id: 'sys-branch',
            title: 'Chi nhánh',
            route: '/admin/system/branches/list',
            activePrefix: '/admin/system/branches',
            authorities: [ROLE.QUAN_LY_CHI_NHANH.VIEW],
          },
          {
            kind: 'child',
            id: 'sys-scope',
            title: 'Phạm vi',
            route: '/admin/system/scopes/list',
            activePrefix: '/admin/system/scopes',
            authorities: [ROLE.QUAN_LY_PHAM_VI.VIEW],
          },
          {
            kind: 'child',
            id: 'sys-hours',
            title: 'Giờ hoạt động',
            route: '/admin/system/branch-hours/list',
            activePrefix: '/admin/system/branch-hours',
            authorities: [ROLE.QUAN_LY_GIO_HOAT_DONG.VIEW],
          },
          {
            kind: 'child',
            id: 'sys-pickup',
            title: 'Khung giờ Pickup',
            route: '/admin/system/pickup-slots/list',
            activePrefix: '/admin/system/pickup-slots',
            authorities: [ROLE.QUAN_LY_KHUNG_GIO_PICKUP.VIEW],
          },
        ],
      },
      {
        kind: 'parent',
        id: 'sys-access',
        title: 'Phân quyền',
        icon: 'safety-certificate',
        children: [
          {
            kind: 'child',
            id: 'sys-account',
            title: 'Người dùng',
            route: '/admin/system/accounts/list',
            activePrefix: '/admin/system/accounts',
            authorities: [ROLE.QUAN_LY_NGUOI_DUNG.VIEW],
          },
          {
            kind: 'child',
            id: 'sys-role',
            title: 'Vai trò',
            route: '/admin/system/roles/list',
            activePrefix: '/admin/system/roles',
            authorities: [ROLE.QUAN_LY_VAI_TRO.VIEW],
          },
          {
            kind: 'child',
            id: 'sys-audit',
            title: 'Nhật ký',
            route: '/admin/system/audit/list',
            activePrefix: '/admin/system/audit',
            authorities: [ROLE.XEM_AUDIT.VIEW],
          },
        ],
      },
      {
        kind: 'parent',
        id: 'sys-platform',
        title: 'Nền tảng',
        icon: 'notification',
        children: [
          {
            kind: 'child',
            id: 'sys-notify',
            title: 'Thông báo',
            route: '/admin/platform/notifications/list',
            activePrefix: '/admin/platform/notifications',
            authorities: [ROLE.THONG_BAO.VIEW],
          },
          {
            kind: 'child',
            id: 'sys-template',
            title: 'Mẫu thông báo',
            route: '/admin/platform/templates/list',
            activePrefix: '/admin/platform/templates',
            authorities: [ROLE.MAU_THONG_BAO.VIEW],
          },
        ],
      },
      {
        kind: 'parent',
        id: 'dev-tools',
        title: 'Công cụ DEV',
        icon: 'tool',
        children: [
          {
            kind: 'child',
            id: 'dev-ui-kit',
            title: 'UI Design System',
            route: '/admin/ui-kit',
            authorities: [FULL_PERMISSION, 'ROLE_ADMIN'],
          },
          {
            kind: 'child',
            id: 'dev-error',
            title: 'Trang lỗi',
            route: '/admin/error-pages',
            authorities: [FULL_PERMISSION, 'ROLE_ADMIN'],
          },
        ],
      },
    ],
  },
];
