import { SidebarGroup } from './sidebar.model';
import { ROLE, FULL_PERMISSION } from '../../core/config/functions.constants';

export const SIDEBAR_MENU: SidebarGroup[] = [
  {
    kind: 'group',
    id: 'main-menu',
    title: 'MAIN MENU',
    items: [
      {
        kind: 'parent',
        id: 'overview',
        title: 'Tổng quan',
        icon: 'home',
        route: '/admin/home',
        children: [],
      },
      {
        kind: 'parent',
        id: 'store',
        title: 'Xem Cửa Hàng (Client)',
        icon: 'shop',
        route: '/store',
        children: [],
      },
      {
        kind: 'parent',
        id: 'ui-kit',
        title: 'UI Design System',
        icon: 'sketch',
        route: '/admin/ui-kit',
        children: [],
        authorities: [FULL_PERMISSION, 'ROLE_ADMIN'],
      },
      {
        kind: 'parent',
        id: 'error-pages',
        title: 'Trang thông báo lỗi',
        icon: 'warning',
        route: '/admin/error-pages',
        children: [],
        authorities: [FULL_PERMISSION, 'ROLE_ADMIN'],
      },
      {
        kind: 'parent',
        id: 'procurement',
        title: 'Mua hàng',
        icon: 'shopping',
        children: [
          {
            kind: 'child',
            id: 'manage-purchase-orders',
            title: 'Đơn mua hàng',
            route: '/admin/procurement/purchase-orders/list',
            activePrefix: '/admin/procurement/purchase-orders',
            authorities: [ROLE.DON_MUA_HANG.VIEW],
          },
          {
            kind: 'child',
            id: 'manage-suppliers',
            title: 'Nhà cung cấp',
            route: '/admin/procurement/suppliers/list',
            activePrefix: '/admin/procurement/suppliers',
            authorities: [ROLE.NHA_CUNG_CAP.VIEW],
          },
        ],
      },
      {
        kind: 'parent',
        id: 'system',
        title: 'Hệ thống',
        icon: 'appstore',
        children: [
          {
            kind: 'child',
            id: 'manage-accounts',
            title: 'Quản lý tài khoản',
            icon: 'team',
            children: [
              {
                kind: 'child',
                id: 'manage-customers',
                title: 'Quản lý khách hàng',
                route: '/admin/system/customers/list',
                activePrefix: '/admin/system/customers',
                authorities: [ROLE.KHACH_HANG.VIEW],
              },
              {
                kind: 'child',
                id: 'manage-internal-accounts',
                title: 'Quản lý người dùng nội bộ',
                route: '/admin/system/accounts/list',
                activePrefix: '/admin/system/accounts',
                authorities: [ROLE.QUAN_LY_NGUOI_DUNG.VIEW],
              },
            ],
          },
          {
            kind: 'child',
            id: 'manage-roles',
            title: 'Quản lý vai trò',
            route: '/admin/system/roles/list',
            activePrefix: '/admin/system/roles',
            authorities: [ROLE.QUAN_LY_VAI_TRO.VIEW],
          },
          {
            kind: 'child',
            id: 'manage-branches',
            title: 'Quản lý chi nhánh',
            route: '/admin/system/branches/list',
            activePrefix: '/admin/system/branches',
            authorities: [ROLE.QUAN_LY_CHI_NHANH.VIEW],
          },
          {
            kind: 'child',
            id: 'manage-scopes',
            title: 'Quản lý phạm vi',
            route: '/admin/system/scopes/list',
            activePrefix: '/admin/system/scopes',
            authorities: [ROLE.QUAN_LY_PHAM_VI.VIEW],
          },
        ],
      },
    ],
  },
];
